/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ConnectWallet: typeof import('./src/components/ConnectWallet.vue')['default']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    HeaderView: typeof import('./src/components/HeaderView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WalletMask: typeof import('./src/components/WalletMask.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
