/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityView: typeof import('./views/marketplace/components/ActivityView.vue')['default']
    BuySuccess: typeof import('./views/marketplace/components/BuySuccess.vue')['default']
    ConnectWallet: typeof import('./components/ConnectWallet.vue')['default']
    CreateUtxoTip: typeof import('./views/marketplace/components/CreateUtxoTip.vue')['default']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    GPT: typeof import('./components/GPTModal/GPT.vue')['default']
    HeaderView: typeof import('./components/HeaderView.vue')['default']
    HoldersView: typeof import('./views/marketplace/components/HoldersView.vue')['default']
    ItemsView: typeof import('./views/marketplace/components/ItemsView.vue')['default']
    ListNft: typeof import('./views/myBrc720/components/ListNft.vue')['default']
    Loading: typeof import('./components/GPTModal/Loading.vue')['default']
    LoadingView: typeof import('./components/LoadingView.vue')['default']
    MyActivityView: typeof import('./views/myBrc720/components/MyActivityView.vue')['default']
    MyCollectionsView: typeof import('./views/myBrc720/components/MyCollectionsView.vue')['default']
    NotData: typeof import('./components/NotData.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TwoConfirm: typeof import('./views/marketplace/components/TwoConfirm.vue')['default']
    WalletMask: typeof import('./components/WalletMask.vue')['default']
  }
  export interface ComponentCustomProperties {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
  }
}
